// src/app/models/mensaje-contact.model.ts
export interface MensajeContact {
  id?: number;             // optional, since it's generated by the backend
  nombre: string;
  email: string;
  asunto: string;
  mensaje: string;
  fechaContacto: Date;
}
